CREATE TABLE IF NOT EXISTS urls (
	id SERIAL PRIMARY KEY,
	short_id VARCHAR(6) UNIQUE NOT NULL,
	original_url TEXT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL,
	access_count INT NOT NULL DEFAULT 0
);
